### ISSUE TITLE
Duplicate of attribute "expression" in documentation

### ISSUE THREAD

**Issue by contra8** [ediarum/ediarum.JAR#2]
See documentation for function [RegisterSurroundWithDifferentFragmentsOperation](https://github.com/ediarum/ediarum.JAR/wiki/Documentation-ediarum.jar#register-surround-with-different-fragments-operation).

The documentation lists the parameter "expression" twice, with different content.

**Comment by StefanDumont** [comment]
Thank you for the hint! I deleted the wrong row.
