### ISSUE TITLE
Document dependencies, e.g. `lib-pdr-dates-plugin-1.2.2-10.jar`

### ISSUE THREAD

**Issue by teoric** [ediarum/ediarum.JAR#5]
This looks like a helpful package.  Building it, however, seems a bit underdocumented.  As a dependency, I found the [Oxygen XML SDK](https://www.oxygenxml.com/oxygen_sdk.html).

But could you point me to `lib-pdr-dates-plugin-1.2.2-10.jar`?

**Comment by MartinFechner** [comment]
Thanks for the question. The missing library is part of a currently unpublished project. You can eliminate the dependency by deleting the folder `src/org/bbaw/telota/ediarum/dates` before compiling.

**Comment by MartinFechner** [comment]
The missing library and information about dependencies will be added in the next release.
