### ISSUE TITLE
Functions renamed?

### ISSUE THREAD

**Issue by teoric** [ediarum/ediarum.JAR#6]
I find that the documented functions do not show up in the Java files, e.g., `org.bbaw.telota.ediarum.InsertLinkOperation`.  This seems to have been renamed to `InsertReferenceForLinkTargetOperation.java` in 53e0941201efbccb11425b9bd7d01c71d99a974a. Would it be possible to update the documentation?

**Comment by MartinFechner** [comment]
Thanks for the info. We will update this.

**Comment by MartinFechner** [comment]
The change will be published with the next release.
